name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Mock-Jwks-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }} 
    python_version: ${{ variables.python_version }}
    apigee_deployments:
      - environment: internal-dev
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: internal-dev-sandbox
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: internal-qa
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: internal-qa-sandbox
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: ref
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: dev
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: int
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: sandbox
        jinja_templates:
          TESTING_ENDPOINTS: true
      - environment: prod
        depends_on:
          - internal_dev
